#ifndef CH32_FT232_UART_FORWARD_CONFIG_H
#define CH32_FT232_UART_FORWARD_CONFIG_H

/* 外部构建只能在这两个 UART 端口之间选择；未定义时固定使用
 * PA2/PA3。命令行 -DUART_FORWARD_PORT=UART_FORWARD_PORT_PB67 可覆盖。
 */
#define UART_FORWARD_PORT_PA23 (0U)
#define UART_FORWARD_PORT_PB67 (1U)

#ifndef UART_FORWARD_PORT
#define UART_FORWARD_PORT UART_FORWARD_PORT_PA23
#endif

#if (UART_FORWARD_PORT != UART_FORWARD_PORT_PA23) && \
    (UART_FORWARD_PORT != UART_FORWARD_PORT_PB67)
#error "UART_FORWARD_PORT must be UART_FORWARD_PORT_PA23 or UART_FORWARD_PORT_PB67"
#endif

/* UART 与 CDC GET_LINE_CODING 共用这一份编译期事实，主机请求不能改写。 */
#define UART_FORWARD_BAUD_RATE       (115200UL)
#define UART_FORWARD_STOP_BITS       (0U)
#define UART_FORWARD_PARITY          (0U)
#define UART_FORWARD_DATA_BITS       (8U)
#define UART_FORWARD_RX_BUFFER_SIZE  (512U)
#define UART_FORWARD_TX_BUFFER_SIZE  (512U)
/* CH32V203 的 512 字节 USB PMA 已被八个端点占满，CDC 数据端点固定为
 * 16 字节；转发服务按同一块大小搬运，不另存一份运行时配置。
 */
#define UART_FORWARD_COPY_CHUNK_SIZE (16U)

#if UART_FORWARD_PORT == UART_FORWARD_PORT_PA23
#define UART_FORWARD_PERIPHERAL_CLOCK_HZ (72000000UL)
#elif UART_FORWARD_PORT == UART_FORWARD_PORT_PB67
#define UART_FORWARD_PERIPHERAL_CLOCK_HZ (144000000UL)
#endif

#endif /* CH32_FT232_UART_FORWARD_CONFIG_H */
