#ifndef CH32_FT232_UART_FORWARD_CONFIG_H
#define CH32_FT232_UART_FORWARD_CONFIG_H

#include "boardtype/20pinout.h"

/* UART 转发共有关闭、PA2/PA3、PB6/PB7 三种编译期配置。关闭时不发布
 * CDC 接口，也不配置 UART GPIO、USART 和 DMA。
 */
#define UART_FORWARD_PORT_PA23 (0U)
#define UART_FORWARD_PORT_PB67 (1U)
#define UART_FORWARD_PORT_DISABLED (2U)

#ifndef UART_FORWARD_PORT
#define UART_FORWARD_PORT UART_FORWARD_PORT_DISABLED
#endif

#if (BOARD_20PINOUT != 0U) && \
    (UART_FORWARD_PORT != UART_FORWARD_PORT_DISABLED) && \
    (UART_FORWARD_PORT != BOARD_20PINOUT_UART_PORT)
#error "BOARD_20PINOUT UART forwarding requires PB6/PB7"
#endif

#if (UART_FORWARD_PORT != UART_FORWARD_PORT_PA23) && \
    (UART_FORWARD_PORT != UART_FORWARD_PORT_PB67) && \
    (UART_FORWARD_PORT != UART_FORWARD_PORT_DISABLED)
#error "UART_FORWARD_PORT must be DISABLED, PA23 or PB67"
#endif

#define UART_FORWARD_ENABLED \
    ((UART_FORWARD_PORT != UART_FORWARD_PORT_DISABLED) ? 1U : 0U)

/* UART 与 CDC GET_LINE_CODING 共用这一份编译期事实，主机请求不能改写。 */
#define UART_FORWARD_BAUD_RATE       (115200UL)
#define UART_FORWARD_STOP_BITS       (0U)
#define UART_FORWARD_PARITY          (0U)
#define UART_FORWARD_DATA_BITS       (8U)
#define UART_FORWARD_RX_BUFFER_SIZE  (512U)
#define UART_FORWARD_TX_BUFFER_SIZE  (512U)
/* CH32V203 的 512 字节 USB PMA 已被八个端点占满，CDC 数据端点固定为
 * 16 字节；转发服务按同一块大小搬运，不另存一份运行时配置。
 */
#define UART_FORWARD_COPY_CHUNK_SIZE (16U)

#if UART_FORWARD_PORT == UART_FORWARD_PORT_PA23
#define UART_FORWARD_PERIPHERAL_CLOCK_HZ (72000000UL)
#elif UART_FORWARD_PORT == UART_FORWARD_PORT_PB67
#define UART_FORWARD_PERIPHERAL_CLOCK_HZ (144000000UL)
#endif

#endif /* CH32_FT232_UART_FORWARD_CONFIG_H */
