#ifndef CH32_FT232_LED_INSTANCES_CONFIG_H
#define CH32_FT232_LED_INSTANCES_CONFIG_H

#include "boardtype/20pinout.h"

/* 当前板子的 PB0 运行灯。无 LED 的板子由构建参数关闭整个实例。 */
#ifndef RUN_LED_ENABLED
#define RUN_LED_ENABLED (1U)
#endif

#if (RUN_LED_ENABLED != 0U) && (RUN_LED_ENABLED != 1U)
#error "RUN_LED_ENABLED must be 0 or 1"
#endif

#if RUN_LED_ENABLED != 0U
#if BOARD_20PINOUT != 0U
#define RUN_LED_GPIO_PORT            BOARD_20PINOUT_RUN_LED_PORT
#define RUN_LED_GPIO_PORT_CLOCK      BOARD_20PINOUT_RUN_LED_PORT_CLOCK
#define RUN_LED_GPIO_PIN_NUMBER      BOARD_20PINOUT_RUN_LED_PIN_NUMBER
#define RUN_LED_ACTIVE_LEVEL         BOARD_20PINOUT_RUN_LED_ACTIVE_LEVEL
#define RUN_LED_OUTPUT_TYPE          BOARD_20PINOUT_RUN_LED_OUTPUT_TYPE
#define RUN_LED_REMAP_REGISTER       BOARD_20PINOUT_RUN_LED_REMAP_REGISTER
#define RUN_LED_REMAP_MASK           BOARD_20PINOUT_RUN_LED_REMAP_MASK
#define RUN_LED_REMAP_VALUE          BOARD_20PINOUT_RUN_LED_REMAP_VALUE
#else
#define RUN_LED_GPIO_PORT            GPIOB
#define RUN_LED_GPIO_PORT_CLOCK      RCC_IOPBEN
#define RUN_LED_GPIO_PIN_NUMBER      (0U)
#define RUN_LED_ACTIVE_LEVEL         LED_ACTIVE_LOW
#define RUN_LED_OUTPUT_TYPE          LED_OUTPUT_OPEN_DRAIN
#define RUN_LED_REMAP_REGISTER       (&AFIO->PCFR1)
#define RUN_LED_REMAP_MASK           (0U)
#define RUN_LED_REMAP_VALUE          (0U)
#endif
#define RUN_LED_SERVICE_PERIOD_TICKS (72000000UL)
#endif

#endif /* CH32_FT232_LED_INSTANCES_CONFIG_H */
