#ifndef CH32_FT232_20PINOUT_H
#define CH32_FT232_20PINOUT_H

/* CMake 通过 BOARD_TYPE=20PINOUT 打开这个宏；其余配置层只认该宏，
 * 不再分别选择 JTAG、UART 和运行灯引脚。
 */
#ifndef BOARD_20PINOUT
#define BOARD_20PINOUT (0U)
#endif

#if (BOARD_20PINOUT != 0U) && (BOARD_20PINOUT != 1U)
#error "BOARD_20PINOUT must be 0 or 1"
#endif

#if BOARD_20PINOUT != 0U

#define BOARD_20PINOUT_JTAG_TCK_CFG GPIO_CFG_PIN(GPIOA, RCC_IOPAEN, 6U)
#define BOARD_20PINOUT_JTAG_TMS_CFG GPIO_CFG_PIN(GPIOA, RCC_IOPAEN, 5U)
#define BOARD_20PINOUT_JTAG_TDI_CFG GPIO_CFG_PIN(GPIOA, RCC_IOPAEN, 4U)
#define BOARD_20PINOUT_JTAG_TDO_CFG GPIO_CFG_PIN(GPIOA, RCC_IOPAEN, 2U)

#define BOARD_20PINOUT_UART_PORT UART_FORWARD_PORT_PB67

#define BOARD_20PINOUT_RUN_LED_PORT         GPIOA
#define BOARD_20PINOUT_RUN_LED_PORT_CLOCK   RCC_IOPAEN
#define BOARD_20PINOUT_RUN_LED_PIN_NUMBER   (15U)
#define BOARD_20PINOUT_RUN_LED_ACTIVE_LEVEL LED_ACTIVE_LOW
#define BOARD_20PINOUT_RUN_LED_OUTPUT_TYPE  LED_OUTPUT_PUSH_PULL
#define BOARD_20PINOUT_RUN_LED_REMAP_REGISTER (&AFIO->PCFR1)
#define BOARD_20PINOUT_RUN_LED_REMAP_MASK     ((uint32_t)AFIO_PCFR1_SWJ_CFG)
/* PA15 是 JTDI；关闭 JTAG-DP 后仍保留 SW-DP，才能把 PA15 交给运行灯。 */
#define BOARD_20PINOUT_RUN_LED_REMAP_VALUE \
    ((uint32_t)AFIO_PCFR1_SWJ_CFG_JTAGDISABLE)

#endif

#endif /* CH32_FT232_20PINOUT_H */
