#ifndef CH32_FT232_20PINOUT_H
#define CH32_FT232_20PINOUT_H

/* 仅由 BoardConfig.h 选择；引脚、外设和板上资源在板型中明确给定。 */
#define BOARD_JTAG_OUTPUT_PORT       GPIOA
#define BOARD_JTAG_OUTPUT_PORT_CLOCK RCC_IOPAEN
#define BOARD_JTAG_TCK_PIN           (6U)
#define BOARD_JTAG_TMS_PIN           (5U)
#define BOARD_JTAG_TDI_PIN           (4U)
#define BOARD_JTAG_TDO_PORT          GPIOA
#define BOARD_JTAG_TDO_PORT_CLOCK    RCC_IOPAEN
#define BOARD_JTAG_TDO_PIN           (2U)

#define BOARD_USB_PORT         GPIOA
#define BOARD_USB_PORT_CLOCK   RCC_IOPAEN
#define BOARD_USB_DM_PIN       (11U)
#define BOARD_USB_DP_PIN       (12U)
#define BOARD_USB_CLOCK_SOURCE RCC_USBCLKSource_PLLCLK_Div3

#define BOARD_HAS_UART (1U)
#include "Ch32V203Usart1Pb67.h"

#define BOARD_HAS_RUN_LED (1U)
#define BOARD_RUN_LED_PORT         GPIOA
#define BOARD_RUN_LED_PORT_CLOCK   RCC_IOPAEN
#define BOARD_RUN_LED_PIN_NUMBER   (15U)
#define BOARD_RUN_LED_ACTIVE_LEVEL LED_ACTIVE_LOW
#define BOARD_RUN_LED_OUTPUT_TYPE  LED_OUTPUT_PUSH_PULL
#define BOARD_RUN_LED_REMAP_REGISTER (&AFIO->PCFR1)
#define BOARD_RUN_LED_REMAP_MASK     ((uint32_t)AFIO_PCFR1_SWJ_CFG)
/* PA15 是 JTDI；关闭 JTAG-DP 后仍保留 SW-DP，才能把 PA15 交给运行灯。 */
#define BOARD_RUN_LED_REMAP_VALUE ((uint32_t)AFIO_PCFR1_SWJ_CFG_JTAGDISABLE)

#endif /* CH32_FT232_20PINOUT_H */
