#ifndef CH32_FT232_22PINOUT_H
#define CH32_FT232_22PINOUT_H

/* CMake 固定选择 22PINOUT。JTAG/UART 按板上布线定义，板上没有运行灯。 */
#ifndef BOARD_22PINOUT
#define BOARD_22PINOUT (0U)
#endif

#if (BOARD_22PINOUT != 0U) && (BOARD_22PINOUT != 1U)
#error "BOARD_22PINOUT must be 0 or 1"
#endif

#if BOARD_22PINOUT != 0U

#define BOARD_22PINOUT_JTAG_TCK_CFG GPIO_CFG_PIN(GPIOA, RCC_IOPAEN, 6U)
#define BOARD_22PINOUT_JTAG_TMS_CFG GPIO_CFG_PIN(GPIOA, RCC_IOPAEN, 7U)
#define BOARD_22PINOUT_JTAG_TDI_CFG GPIO_CFG_PIN(GPIOA, RCC_IOPAEN, 5U)
#define BOARD_22PINOUT_JTAG_TDO_CFG GPIO_CFG_PIN(GPIOA, RCC_IOPAEN, 4U)

#define BOARD_22PINOUT_UART_PORT UART_FORWARD_PORT_PB67

#endif

#endif /* CH32_FT232_22PINOUT_H */
