#ifndef CH32_FT232_BOARD_CONFIG_H
#define CH32_FT232_BOARD_CONFIG_H

#include "20pinout.h"
#include "22pinout.h"

/* 板型只在这里选择，GPIO、UART 和 LED 通过同一组宏取得板级约束。 */
#if (BOARD_20PINOUT + BOARD_22PINOUT) > 1U
#error "Only one board type may be selected"
#endif

#if BOARD_20PINOUT != 0U

#define BOARD_CUSTOM_PINOUT  (1U)
#define BOARD_JTAG_TCK_CFG   BOARD_20PINOUT_JTAG_TCK_CFG
#define BOARD_JTAG_TMS_CFG   BOARD_20PINOUT_JTAG_TMS_CFG
#define BOARD_JTAG_TDI_CFG   BOARD_20PINOUT_JTAG_TDI_CFG
#define BOARD_JTAG_TDO_CFG   BOARD_20PINOUT_JTAG_TDO_CFG
#define BOARD_UART_PORT     BOARD_20PINOUT_UART_PORT
#define BOARD_HAS_RUN_LED   (1U)
#define BOARD_RUN_LED_CUSTOM (1U)
#define BOARD_RUN_LED_PORT         BOARD_20PINOUT_RUN_LED_PORT
#define BOARD_RUN_LED_PORT_CLOCK   BOARD_20PINOUT_RUN_LED_PORT_CLOCK
#define BOARD_RUN_LED_PIN_NUMBER   BOARD_20PINOUT_RUN_LED_PIN_NUMBER
#define BOARD_RUN_LED_ACTIVE_LEVEL BOARD_20PINOUT_RUN_LED_ACTIVE_LEVEL
#define BOARD_RUN_LED_OUTPUT_TYPE  BOARD_20PINOUT_RUN_LED_OUTPUT_TYPE
#define BOARD_RUN_LED_REMAP_REGISTER BOARD_20PINOUT_RUN_LED_REMAP_REGISTER
#define BOARD_RUN_LED_REMAP_MASK     BOARD_20PINOUT_RUN_LED_REMAP_MASK
#define BOARD_RUN_LED_REMAP_VALUE    BOARD_20PINOUT_RUN_LED_REMAP_VALUE

#elif BOARD_22PINOUT != 0U

#define BOARD_CUSTOM_PINOUT  (1U)
#define BOARD_JTAG_TCK_CFG   BOARD_22PINOUT_JTAG_TCK_CFG
#define BOARD_JTAG_TMS_CFG   BOARD_22PINOUT_JTAG_TMS_CFG
#define BOARD_JTAG_TDI_CFG   BOARD_22PINOUT_JTAG_TDI_CFG
#define BOARD_JTAG_TDO_CFG   BOARD_22PINOUT_JTAG_TDO_CFG
#define BOARD_UART_PORT     BOARD_22PINOUT_UART_PORT
#define BOARD_HAS_RUN_LED   (0U)
#define BOARD_RUN_LED_CUSTOM (0U)

#else

#define BOARD_CUSTOM_PINOUT  (0U)
#define BOARD_HAS_RUN_LED   (1U)
#define BOARD_RUN_LED_CUSTOM (0U)

#endif

#endif /* CH32_FT232_BOARD_CONFIG_H */
