#ifndef CH32_FT232_BOARD_USART2_PA23_H
#define CH32_FT232_BOARD_USART2_PA23_H

/* USART2 默认映射到 PA2/PA3，沿用原 PA23 实现的 APB1 和 DMA1 路由。 */
#define BOARD_UART_GPIO_PORT       GPIOA
#define BOARD_UART_GPIO_PORT_CLOCK RCC_IOPAEN
#define BOARD_UART_TX_PIN          (2U)
#define BOARD_UART_RX_PIN          (3U)
#define BOARD_UART_REMAP_REGISTER  (&AFIO->PCFR1)
#define BOARD_UART_REMAP_MASK      ((uint32_t)AFIO_PCFR1_USART2_REMAP)
#define BOARD_UART_REMAP_VALUE     (0U)

#define BOARD_UART_PERIPHERAL          USART2
#define BOARD_UART_PERIPHERAL_CLOCK_HZ (72000000UL)
#define BOARD_UART_CLOCK_REGISTER      (&RCC->APB1PCENR)
#define BOARD_UART_RESET_REGISTER      (&RCC->APB1PRSTR)
#define BOARD_UART_CLOCK_MASK          RCC_USART2EN
#define BOARD_UART_RESET_MASK          RCC_USART2RST

#define BOARD_UART_DMA                DMA1
#define BOARD_UART_DMA_CLOCK_REGISTER (&RCC->AHBPCENR)
#define BOARD_UART_DMA_CLOCK_MASK     RCC_DMA1EN
#define BOARD_UART_RX_DMA             DMA1_Channel6
#define BOARD_UART_TX_DMA             DMA1_Channel7
#define BOARD_UART_RX_DMA_IRQ         DMA1_Channel6_IRQn
#define BOARD_UART_RX_DMA_IRQ_HANDLER DMA1_Channel6_IRQHandler
#define BOARD_UART_RX_DMA_GLOBAL_FLAG DMA_CGIF6
#define BOARD_UART_RX_DMA_DONE_FLAG   DMA_TCIF6
#define BOARD_UART_RX_DMA_ERROR_FLAG  DMA_TEIF6
#define BOARD_UART_TX_DMA_GLOBAL_FLAG DMA_CGIF7
#define BOARD_UART_TX_DMA_DONE_FLAG   DMA_TCIF7
#define BOARD_UART_TX_DMA_ERROR_FLAG  DMA_TEIF7

#endif /* CH32_FT232_BOARD_USART2_PA23_H */
