#ifndef CH32_FT232_BOARD_USART1_PB67_H
#define CH32_FT232_BOARD_USART1_PB67_H

/* 两种现有板型显式复用 USART1 的 PB6/PB7 布线；驱动不再选择硬件路由。 */
#define BOARD_UART_GPIO_PORT       GPIOB
#define BOARD_UART_GPIO_PORT_CLOCK RCC_IOPBEN
#define BOARD_UART_TX_PIN          (6U)
#define BOARD_UART_RX_PIN          (7U)
#define BOARD_UART_REMAP_REGISTER  (&AFIO->PCFR1)
#define BOARD_UART_REMAP_MASK      ((uint32_t)AFIO_PCFR1_USART1_REMAP)
#define BOARD_UART_REMAP_VALUE     ((uint32_t)AFIO_PCFR1_USART1_REMAP)

#define BOARD_UART_PERIPHERAL          USART1
#define BOARD_UART_PERIPHERAL_CLOCK_HZ (144000000UL)
#define BOARD_UART_CLOCK_REGISTER      (&RCC->APB2PCENR)
#define BOARD_UART_RESET_REGISTER      (&RCC->APB2PRSTR)
#define BOARD_UART_CLOCK_MASK          RCC_USART1EN
#define BOARD_UART_RESET_MASK          RCC_USART1RST

#define BOARD_UART_DMA                DMA1
#define BOARD_UART_DMA_CLOCK_REGISTER (&RCC->AHBPCENR)
#define BOARD_UART_DMA_CLOCK_MASK     RCC_DMA1EN
#define BOARD_UART_RX_DMA             DMA1_Channel5
#define BOARD_UART_TX_DMA             DMA1_Channel4
#define BOARD_UART_RX_DMA_IRQ         DMA1_Channel5_IRQn
#define BOARD_UART_RX_DMA_IRQ_HANDLER DMA1_Channel5_IRQHandler
#define BOARD_UART_RX_DMA_GLOBAL_FLAG DMA_CGIF5
#define BOARD_UART_RX_DMA_DONE_FLAG   DMA_TCIF5
#define BOARD_UART_RX_DMA_ERROR_FLAG  DMA_TEIF5
#define BOARD_UART_TX_DMA_GLOBAL_FLAG DMA_CGIF4
#define BOARD_UART_TX_DMA_DONE_FLAG   DMA_TCIF4
#define BOARD_UART_TX_DMA_ERROR_FLAG  DMA_TEIF4

#endif /* CH32_FT232_BOARD_USART1_PB67_H */
