# userconfig 只接受 GUI 写出的 set(KEY "VALUE") 数据，不执行其中的 CMake 命令。
function(pinselect_load_config config_file board_directory)
    if(NOT EXISTS "${config_file}")
        message(FATAL_ERROR "Missing ${config_file}. Run python3 PinSelectGUI/pinselect.py and save a configuration first.")
    endif()
    set(_base_keys USER_CONFIG_VERSION USER_BOARD_MODE)
    set(_custom_keys USER_JTAG_TCK USER_JTAG_TMS USER_JTAG_TDI USER_JTAG_TDO USER_UART_MODE)
    set(_allowed_keys ${_base_keys} ${_custom_keys})
    set(_seen_keys "")
    foreach(_key IN LISTS _allowed_keys)
        set(${_key} "")
    endforeach()
    file(STRINGS "${config_file}" _lines ENCODING UTF-8)
    foreach(_line IN LISTS _lines)
        string(STRIP "${_line}" _line)
        if(_line STREQUAL "" OR _line MATCHES "^#")
            continue()
        endif()
        if(NOT _line MATCHES "^set\\(([A-Z_]+)[ \t]+\"([A-Za-z0-9_]+)\"\\)$")
            message(FATAL_ERROR "Invalid userconfig line: ${_line}")
        endif()
        set(_key "${CMAKE_MATCH_1}")
        set(_value "${CMAKE_MATCH_2}")
        if(NOT _key IN_LIST _allowed_keys OR _key IN_LIST _seen_keys)
            message(FATAL_ERROR "Unknown or duplicate userconfig key: ${_key}")
        endif()
        list(APPEND _seen_keys "${_key}")
        set(${_key} "${_value}")
    endforeach()
    if(NOT USER_CONFIG_VERSION STREQUAL "1")
        message(FATAL_ERROR "userconfig requires USER_CONFIG_VERSION=1")
    endif()
    set(PINSELECT_MODE "${USER_BOARD_MODE}")
    if(PINSELECT_MODE STREQUAL "20PINOUT" OR PINSELECT_MODE STREQUAL "22PINOUT")
        foreach(_key IN LISTS _custom_keys)
            if(_key IN_LIST _seen_keys)
                message(FATAL_ERROR "Preset ${PINSELECT_MODE} cannot override ${_key}; select CUSTOM first")
            endif()
        endforeach()
        string(TOLOWER "${PINSELECT_MODE}" _preset_name)
        set(_preset_file "${board_directory}/${_preset_name}.h")
        file(READ "${_preset_file}" _preset)
        # 预设直接读取现有板型头，不能在 CMake 中复制另一套引脚数值。
        foreach(_port IN ITEMS OUTPUT TDO)
            if(NOT _preset MATCHES "#define[ \t]+BOARD_JTAG_${_port}_PORT[ \t]+GPIOA[\r\n]")
                message(FATAL_ERROR "Preset ${PINSELECT_MODE} must use GPIOA for this GUI")
            endif()
        endforeach()
        foreach(_signal IN ITEMS TCK TMS TDI TDO)
            if(NOT _preset MATCHES "#define[ \t]+BOARD_JTAG_${_signal}_PIN[ \t]+\\(([0-7])U\\)")
                message(FATAL_ERROR "Missing PA0..PA7 ${_signal} definition in ${_preset_file}")
            endif()
            set(PINSELECT_${_signal} "PA${CMAKE_MATCH_1}")
        endforeach()
        if(NOT _preset MATCHES "#include[ \t]+\"Ch32V203Usart[12](Pa23|Pb67)\\.h\"")
            message(FATAL_ERROR "Missing supported UART route in ${_preset_file}")
        endif()
        string(TOUPPER "${CMAKE_MATCH_1}" PINSELECT_UART)
        set(PINSELECT_BOARD_DEFINE "BOARD_${PINSELECT_MODE}=1U")
    elseif(PINSELECT_MODE STREQUAL "CUSTOM")
        foreach(_key IN LISTS _custom_keys)
            if(NOT _key IN_LIST _seen_keys)
                message(FATAL_ERROR "Missing userconfig key: ${_key}")
            endif()
        endforeach()
        foreach(_signal IN ITEMS TCK TMS TDI TDO)
            set(PINSELECT_${_signal} "${USER_JTAG_${_signal}}")
        endforeach()
        set(PINSELECT_UART "${USER_UART_MODE}")
        set(PINSELECT_BOARD_DEFINE "BOARD_USER=1U")
    else()
        message(FATAL_ERROR "USER_BOARD_MODE must be 20PINOUT, 22PINOUT or CUSTOM")
    endif()

    set(_used_pins "")
    foreach(_signal IN ITEMS TCK TMS TDI TDO)
        set(_pin "${PINSELECT_${_signal}}")
        if(NOT _pin MATCHES "^PA([0-7])$")
            message(FATAL_ERROR "JTAG ${_signal} must select PA0..PA7, got ${_pin}")
        endif()
        set(PINSELECT_${_signal}_INDEX "${CMAKE_MATCH_1}")
        if(_pin IN_LIST _used_pins)
            message(FATAL_ERROR "Duplicate JTAG pin: ${_pin} (${_signal})")
        endif()
        list(APPEND _used_pins "${_pin}")
    endforeach()
    set(PINSELECT_UART_PA23 0)
    set(PINSELECT_UART_PB67 0)
    set(PINSELECT_HAS_UART 1)
    if(PINSELECT_UART STREQUAL "PA23")
        if("PA2" IN_LIST _used_pins OR "PA3" IN_LIST _used_pins)
            message(FATAL_ERROR "UART PA23 conflicts with JTAG on PA2/PA3")
        endif()
        set(PINSELECT_UART_PA23 1)
        set(PINSELECT_UART_DESCRIPTION "PA23: TX=PA2, RX=PA3, USART2")
    elseif(PINSELECT_UART STREQUAL "PB67")
        set(PINSELECT_UART_PB67 1)
        set(PINSELECT_UART_DESCRIPTION "PB67: TX=PB6, RX=PB7, USART1")
    elseif(PINSELECT_UART STREQUAL "DISABLED")
        set(PINSELECT_HAS_UART 0)
        set(PINSELECT_UART_DESCRIPTION "DISABLED")
    else()
        message(FATAL_ERROR "USER_UART_MODE must be PA23, PB67 or DISABLED")
    endif()

    if(NOT CMAKE_SCRIPT_MODE_FILE)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${config_file}")
        if(DEFINED _preset_file)
            set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_preset_file}")
        endif()
    endif()
    foreach(_name IN ITEMS MODE UART BOARD_DEFINE UART_PA23 UART_PB67 HAS_UART UART_DESCRIPTION
            TCK TMS TDI TDO TCK_INDEX TMS_INDEX TDI_INDEX TDO_INDEX)
        set(PINSELECT_${_name} "${PINSELECT_${_name}}" PARENT_SCOPE)
    endforeach()
endfunction()
